from .users import *
from .testimonial import *
from .faq import *
from .clients import *
from .blogs import *
from .gallery import *
from .slider import *
from .counter import *
from .web_setting import *
from .healthteam import *
from .village_care import *
from .web_setting import *