from .homeview import *
from .authview import *
from .patientview import *
from .doctorview import *
from .blogview import *
from .galleryview import *
from .medicinebank import *
from .healthteamview import *
from .villagecareview import *